### ISSUE TITLE
Cannot inherit gorm repository

### ISSUE THREAD

**Issue by VDVT** [aklinkert/go-gorm-repository#1]
![image](https://user-images.githubusercontent.com/18101217/149313217-cff61f14-be55-4b6c-9a63-a4393a874dd6.png)

I try to create my base repository and it will inherit your repository but it's not exported

**Comment by aklinkert** [comment]
Hey @VDVT !

Yeah, the struct itself is not exported, I usually only depend on interfaces. So what you could do is to embed the interface and implement a custom constructor like this:

```go

type BaseRepository interface {
	generic.TransactionRepository
	GetOneByName(target interface{}, name string, preloads ...string) error
}

type repository struct {
	generic.TransactionRepository
}

func NewRepository(db *gorm.DB, logger logging.Logger) BaseRepository {
	return &repository{
		TransactionRepository: generic.NewBaseRepository(db, logger, "Creator"),
	}
}

func (r *repository) GetOneByName(target interface{}, name string, preloads ...string) error {
	return r.TransactionRepository.GetOneByField(target, "name", name, preloads...)
}

```

Hope that helps!
